CREATE TABLE USER(
userID INT NOT NULL,
lpassword TEXT NOT NULL,
isPremium BOOL NOT NULL DEFAULT 0,
summary TEXT,
sector TEXT,
powerOfProfile SMALLINT NOT NULL DEFAULT 0,
country TEXT,
city TEXT,
firstName TEXT NOT NULL,
lastName TEXT NOT NULL,
title TEXT,
currentPosition TEXT,
PRIMARY KEY(userID)
);

INSERT INTO USER VALUES(1,'abc123',0,'a computer engineer','computer science',2,'Türkiye','İstanbul','Ali','Veli','mühendis','web developer');
INSERT INTO USER VALUES(2,'1997alexa',0,'an engineer','computer engineering',2,'UK','Birmingham','Alexa','Chung','engineer','embedded system engineer');
INSERT INTO USER VALUES(3,'esra96',1,'bireysel ve grup terapisi','eğitim',5,'Türkiye','İzmir','Esra','Köse','psikolog','uzman klinik psikolog');
INSERT INTO USER VALUES(4,'burcu104',0,'bir mimar','güzel sanatlar',3,'Türkiye','Ankara','Burcu','Çadır','mimar','mimar');
INSERT INTO USER VALUES(5,'1234adriana',1,'an engineer','civil engineering',1,'England','Londra','Adriana','Mortez','engineer','civil engineer');
INSERT INTO USER VALUES(6,'asd012',0,'insan kaynakları','halkla ilişkiler',3,'Türkiye','Antalya','Murat','Gözdağ','müdür','insan kaynakları müdürü');
INSERT INTO USER VALUES(7,'18pro18',0,'an engineer','industry engineering',2,'USA','New York','John','Watson','engineer','industry engineer');
INSERT INTO USER VALUES(8,'mehmet1453',1,'akademisyen','eğitim',4,'Türkiye','İzmir','Mehmet','Pala','karşılaştırmalı edebiyat','profesör');
INSERT INTO USER VALUES(9,'klm147',0,'gıda mühendisi','et ve süt teknolojileri',3,'Türkiye','Aydın','Esma','Bozgun','mühendis','mikrobiyolog');
INSERT INTO USER VALUES(10,'123123',1,'Doktorand','Quantenphysik',5,'Deutschland','Berlin','Mark','Zweig','Ingenieur','Physikingenieur');


CREATE TABLE OLD_POSITIONS(
userID INT NOT NULL,
oldPosition VARCHAR(300),
PRIMARY KEY(userID,oldPosition),
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO OLD_POSITIONS VALUES(1,'front-end developer at Linovi');
INSERT INTO OLD_POSITIONS VALUES(1,'manager of big data project');
INSERT INTO OLD_POSITIONS VALUES(2,'embedded system programmer');
INSERT INTO OLD_POSITIONS VALUES(2,'manager of big data project');
INSERT INTO OLD_POSITIONS VALUES(3,'anaokulu müdürü');
INSERT INTO OLD_POSITIONS VALUES(4,'algeç inşaat mimarlık');
INSERT INTO OLD_POSITIONS VALUES(9,'Sütaşta denetleme müdürü');



CREATE TABLE EDU(
userID INT NOT NULL,
education VARCHAR(200),
PRIMARY KEY(userID,education),
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO EDU VALUES(1,'IYTE Bilgisayar Mühendisliği');
INSERT INTO EDU VALUES(2,'Department of Computer Science in University of Oxford');
INSERT INTO EDU VALUES(3,'Lisans: Ege Üniversitesi Psikoloji');
INSERT INTO EDU VALUES(3,'Yüksek Lisans: Ege Üniversitesi Psikoloji');
INSERT INTO EDU VALUES(3,'Doktora: Yaşar Üniversitesi Psikoloji');
INSERT INTO EDU VALUES(4,'Mimar Sinan Güzel Sanatlar Fakültesi Mimarlık');
INSERT INTO EDU VALUES(5,'Bachelor: Civil Engineering in University of Brown');
INSERT INTO EDU VALUES(5,'Master: Civil Engineering in University of Toronto');
INSERT INTO EDU VALUES(6,'Akdeniz Üniversitesi Halkla ilişkiler');
INSERT INTO EDU VALUES(7,'University of California, Industry Engineering ');
INSERT INTO EDU VALUES(8,'İstanbul Üniversitesi Edebiyat Fakültesi');
INSERT INTO EDU VALUES(9,'Nazilli Fen Lisesi');
INSERT INTO EDU VALUES(9,'Adnan Menderes Üniversitesi Gıda Mühendisliği');
INSERT INTO EDU VALUES(10,'Technische Universität München, Physikingenieur');


CREATE TABLE INFO(
userID INT NOT NULL,
contact_info VARCHAR(30),
PRIMARY KEY(userID,contact_info),
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO INFO VALUES(1,'aliveli@iyte.edu.tr');
INSERT INTO INFO VALUES(1,'aliveli@gmail.com');
INSERT INTO INFO VALUES(2,'alexa@gmail.com');
INSERT INTO INFO VALUES(3,'esrakose@ege.edu.tr');
INSERT INTO INFO VALUES(4,'burcucadir@gmail.com');
INSERT INTO INFO VALUES(5,'adriana@gmail.com');
INSERT INTO INFO VALUES(6,'murat@gmail.com');
INSERT INTO INFO VALUES(7,'john@gmail.com');
INSERT INTO INFO VALUES(8,'mehmet@gmail.com');
INSERT INTO INFO VALUES(9,'esma@gmail.com');
INSERT INTO INFO VALUES(10,'mark@gmail.com');
INSERT INTO INFO VALUES(10,'mark@munchen.edu.de');
INSERT INTO INFO VALUES(10,'mark@outlook.com.de');


CREATE TABLE CV(
cvID INT NOT NULL,
userID INT NOT NULL,
realDate DATE,
PRIMARY KEY(cvID),
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO CV VALUES(10,1,'2010-01-10');
INSERT INTO CV VALUES(20,2,'2009-12-15');
INSERT INTO CV VALUES(30,3,'2018-04-08');
INSERT INTO CV VALUES(40,4,'2015-05-12');
INSERT INTO CV VALUES(50,5,'2017-01-20');
INSERT INTO CV VALUES(60,6,'2011-08-10');
INSERT INTO CV VALUES(70,7,'2009-12-05');
INSERT INTO CV VALUES(80,8,'2018-03-19');
INSERT INTO CV VALUES(90,9,'2013-05-12');
INSERT INTO CV VALUES(100,10,'2017-07-20');
INSERT INTO CV VALUES(101,10,'2017-07-23');

CREATE TABLE HONOURSAWARDS(
cvID INT NOT NULL,
title VARCHAR(60) NOT NULL,
PRIMARY KEY(cvID,title),
FOREIGN KEY (cvID) REFERENCES CV(cvID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO HONOURSAWARDS VALUES(10,'certificate of informatic honour');
INSERT INTO HONOURSAWARDS VALUES(30,'en iyi aile danışmanı ödülü');
INSERT INTO HONOURSAWARDS VALUES(30,'türk psikologlar derneği teşekkür belgesi');
INSERT INTO HONOURSAWARDS VALUES(30,'tübitak yüksek lisans bursu');
INSERT INTO HONOURSAWARDS VALUES(90,'Tübitak bilim olimpiyatı ödülü');
INSERT INTO HONOURSAWARDS VALUES(100,'Nobel-Physik-Preis');

CREATE TABLE ORGANIZATION(
cvID INT NOT NULL,
organizationName VARCHAR(25) NOT NULL,
PRIMARY KEY(cvID,organizationName),
FOREIGN KEY (cvID) REFERENCES CV(cvID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO ORGANIZATION VALUES(10,'Genç Mühendisler');
INSERT INTO ORGANIZATION VALUES(60,'Tanıtım');
INSERT INTO ORGANIZATION VALUES(90,'Girişimcilik');

CREATE TABLE LESSON(
cvID INT NOT NULL,
lessonName VARCHAR(50) NOT NULL,
isCertificated BOOL DEFAULT 0,
PRIMARY KEY(cvID,lessonName),
FOREIGN KEY (cvID) REFERENCES CV(cvID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO LESSON VALUES(10,'Etkili iletişim ve beden dili',1);
INSERT INTO LESSON VALUES(30,'Çocuk yetiştirmede nelere dikkat etmeli',1);
INSERT INTO LESSON VALUES(30,'Oyun terapisi eğitimi',1);
INSERT INTO LESSON VALUES(30,'Bilişsel Davranışçı terapi eğitimi',1);
INSERT INTO LESSON VALUES(60,'İşaret dili',0);
INSERT INTO LESSON VALUES(90,'Excel Eğitimi',1);
INSERT INTO LESSON VALUES(90,'Microsoft Word Eğitimi',1);
INSERT INTO LESSON VALUES(90,'Matlab Eğitimi',1);

CREATE TABLE lLANGUAGE(
cvID INT NOT NULL,
languageName VARCHAR(15) NOT NULL,
languageLevel TEXT NOT NULL,
PRIMARY KEY(cvID,languageName),
FOREIGN KEY (cvID) REFERENCES CV(cvID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO lLANGUAGE VALUES(10,'Spanish','B1');
INSERT INTO lLANGUAGE VALUES(10,'English','C2');
INSERT INTO lLANGUAGE VALUES(20,'German','B2');
INSERT INTO lLANGUAGE VALUES(30,'Italian','A2');
INSERT INTO lLANGUAGE VALUES(30,'English','B2');
INSERT INTO lLANGUAGE VALUES(50,'French','B2');
INSERT INTO lLANGUAGE VALUES(70,'French','A2');
INSERT INTO lLANGUAGE VALUES(80,'German','B1');
INSERT INTO lLANGUAGE VALUES(100,'English','C2');

CREATE TABLE PUBLISHING(
cvID INT NOT NULL,
publishingContent VARCHAR(100) NOT NULL,
PRIMARY KEY(cvID,publishingContent),
FOREIGN KEY (cvID) REFERENCES CV(cvID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO PUBLISHING VALUES(30,'Oyun terapisinin çocukların özyeterliliğinde etkileri');
INSERT INTO PUBLISHING VALUES(30,'evcil hayvan terapisi ve yaşam doyumu arasındaki ilişki');
INSERT INTO PUBLISHING VALUES(80,'Karşılaştırmalı Edebiyat: tanım, yöntem ve incelemeler');
INSERT INTO PUBLISHING VALUES(80,'Edebi Tercümeler');
INSERT INTO PUBLISHING VALUES(100,'Quantenphysik und künstliche Intelligenz');
INSERT INTO PUBLISHING VALUES(100,'effects of quantum physics to today');

CREATE TABLE PROJECT(
cvID INT NOT NULL,
projectTitle VARCHAR(80) NOT NULL,
PRIMARY KEY(cvID,projectTitle),
FOREIGN KEY (cvID) REFERENCES CV(cvID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO PROJECT VALUES(20,'Water level Controller using microcontroller');
INSERT INTO PROJECT VALUES(20,'Propeller LED Display');
INSERT INTO PROJECT VALUES(30,'Çocuklarda sosyoduygusal gelişim desteklenmesi projesi');
INSERT INTO PROJECT VALUES(90,'atıkları hayata geri kazandıralım projesi');
INSERT INTO PROJECT VALUES(100,'Particle accelerator');


CREATE TABLE PATENT(
cvID INT NOT NULL,
patentName VARCHAR(50) NOT NULL,
PRIMARY KEY(cvID,patentName),
FOREIGN KEY (cvID) REFERENCES CV(cvID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO PATENT VALUES(70,'Yangın Söndürme Bombası');


CREATE TABLE SETTINGS(
setID INT NOT NULL,
userID INT NOT NULL,
setPrivacy VARCHAR(10) DEFAULT 'PUBLIC',
howToBeSeen VARCHAR(15) NOT NULL DEFAULT'NAME&SURNAME',
reactivity TEXT,
PRIMARY KEY(setID),
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO SETTINGS VALUES(100,1,'private','name&surname','active');
INSERT INTO SETTINGS VALUES(200,2,'private','name&surname','active');
INSERT INTO SETTINGS VALUES(300,3,'public','name&surname','active');
INSERT INTO SETTINGS VALUES(400,4,'private','name&surname','active');
INSERT INTO SETTINGS VALUES(500,5,'public','name&surname','passive');
INSERT INTO SETTINGS VALUES(600,6,'public','surname&name','active');
INSERT INTO SETTINGS VALUES(700,7,'private','name&surname','active');
INSERT INTO SETTINGS VALUES(800,8,'public','name&surname','active');
INSERT INTO SETTINGS VALUES(900,9,'private','name&surname','active');
INSERT INTO SETTINGS VALUES(1000,10,'public','name&surname','active');


CREATE TABLE CAREER_INTERESTS(
careerID INT NOT NULL,
userID INT NOT NULL,
sector TEXT NOT NULL,
title TEXT NOT NULL,
l_when DATE NOT NULL,
CHECK (l_when>CURDATE()),
l_Where TEXT NOT NULL,
PRIMARY KEY(careerID),
FOREIGN KEY(userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT CAREER_INTERESTS VALUES(1000,1,'computer science','engineer','2018-12-20','İstanbul');
INSERT CAREER_INTERESTS VALUES(2000,2,'computer engineering','engineer','2017-05-14','Birmingham');
INSERT CAREER_INTERESTS VALUES(3000,3,'eğitim','psikolog','2015-09-11','İzmir');
INSERT CAREER_INTERESTS VALUES(4000,4,'güzel sanatlar','mimar','2018-06-21','Ankara');
INSERT CAREER_INTERESTS VALUES(5000,5,'civil engineering','engineer','2018-02-12','Londra');
INSERT CAREER_INTERESTS VALUES(6000,6,'halkla ilişkiler','müdür','2016-11-13','Antalya');
INSERT CAREER_INTERESTS VALUES(7000,7,'industry engineering','engineer','2012-04-25','New York');
INSERT CAREER_INTERESTS VALUES(8000,8,'eğitim','profesör','2000-05-29','İzmir');
INSERT CAREER_INTERESTS VALUES(9000,9,'gıda mühendisliği','mühendis','2016-07-20','Aydın');
INSERT CAREER_INTERESTS VALUES(10000,10,'quantenphysik','Ingenieur','2011-01-01','Berlin');


CREATE TABLE UPLOADS(
careerID INT NOT NULL,
userID INT NOT NULL,
upload_date DATE NOT NULL,
PRIMARY KEY(userID,careerID),
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(careerID) REFERENCES CAREER_INTERESTS(careerID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO UPLOADS VALUES(1000,1,'2015-01-01');
INSERT INTO UPLOADS VALUES(2000,2,'2018-05-24');
INSERT INTO UPLOADS VALUES(3000,3,'2017-09-03');
INSERT INTO UPLOADS VALUES(4000,4,'2015-10-21');
INSERT INTO UPLOADS VALUES(5000,5,'2018-05-21');
INSERT INTO UPLOADS VALUES(6000,6,'2017-10-30');
INSERT INTO UPLOADS VALUES(7000,7,'2015-11-01');
INSERT INTO UPLOADS VALUES(8000,8,'2018-05-23');
INSERT INTO UPLOADS VALUES(9000,9,'2017-07-19');
INSERT INTO UPLOADS VALUES(10000,10,'2017-09-11');

CREATE TABLE PAGE_TYPE(
pageTypeID INT NOT NULL,
userID int NOT NULL,
about TEXT,
PRIMARY KEY(pageTypeID),
FOREIGN KEY(userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO PAGE_TYPE VALUES(100000,1,'bilgisayar mühendisliği');
INSERT INTO PAGE_TYPE VALUES(200000,1,'web developers');
INSERT INTO PAGE_TYPE VALUES(300000,4,'modern tasarımlar');
INSERT INTO PAGE_TYPE VALUES(400000,3,'terapi eğitimleri');
INSERT INTO PAGE_TYPE VALUES(500000,7,'Inotech');
INSERT INTO PAGE_TYPE VALUES(600000,6,'Pınar');
INSERT INTO PAGE_TYPE VALUES(700000,5,'Vestel');

CREATE TABLE lPAGE(
pageTypeID INT NOT NULL,
pageType TEXT NOT NULL,
PRIMARY KEY(pageTypeID),
FOREIGN KEY (pageTypeID) REFERENCES PAGE_TYPE(pageTypeID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO lPAGE VALUES(200000,'bilim');

CREATE TABLE COMMUNITY(
pageTypeID INT NOT NULL,
comm_type TEXT NOT NULL,
PRIMARY KEY(pageTypeID),
FOREIGN KEY(pageTypeID) REFERENCES PAGE_TYPE(pageTypeID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO COMMUNITY VALUES(100000,'public');

CREATE TABLE lGROUP(
pageTypeID INT NOT NULL,
groupPrivacy TEXT NOT NULL,
PRIMARY KEY(pageTypeID),
FOREIGN KEY(pageTypeID) REFERENCES PAGE_TYPE(pageTypeID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO lGROUP VALUES(300000,'private');
INSERT INTO lGROUP VALUES(400000,'public');

CREATE TABLE BUSINESS(
pageTypeID INT NOT NULL,
noOfWorkers INT,
PRIMARY KEY(pageTypeID),
FOREIGN KEY(pageTypeID) REFERENCES PAGE_TYPE(pageTypeID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO BUSINESS VALUES(500000,80);
INSERT INTO BUSINESS VALUES(600000,50);
INSERT INTO BUSINESS VALUES(700000,1000);


CREATE TABLE FOLLOWING(
pageTypeID INT NOT NULL,
userID INT NOT NULL,
followingDate DATE NOT NULL,
PRIMARY KEY(userID,pageTypeID),
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(pageTypeID) REFERENCES PAGE_TYPE(pageTypeID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO FOLLOWING VALUES(100000,2,'2018-12-12');
INSERT INTO FOLLOWING VALUES(100000,5,'2017-09-11');
INSERT INTO FOLLOWING VALUES(100000,3,'2018-02-10');
INSERT INTO FOLLOWING VALUES(100000,4,'2018-12-24');
INSERT INTO FOLLOWING VALUES(100000,10,'2017-01-11');
INSERT INTO FOLLOWING VALUES(100000,8,'2018-02-03');
INSERT INTO FOLLOWING VALUES(200000,5,'2017-04-05');
INSERT INTO FOLLOWING VALUES(200000,3,'2018-01-30');
INSERT INTO FOLLOWING VALUES(200000,1,'2017-10-05');
INSERT INTO FOLLOWING VALUES(300000,8,'2018-11-18');
INSERT INTO FOLLOWING VALUES(300000,9,'2016-12-08');
INSERT INTO FOLLOWING VALUES(300000,1,'2018-09-17');
INSERT INTO FOLLOWING VALUES(300000,2,'2017-12-30');
INSERT INTO FOLLOWING VALUES(400000,8,'2018-04-09');
INSERT INTO FOLLOWING VALUES(400000,7,'2018-07-22');
INSERT INTO FOLLOWING VALUES(400000,2,'2017-08-13');
INSERT INTO FOLLOWING VALUES(500000,1,'2018-10-27');
INSERT INTO FOLLOWING VALUES(500000,2,'2017-05-23');


CREATE TABLE CREATES(   /*sayfayı oluşturan*/
pageTypeID INT NOT NULL,
userID INT NOT NULL,
pageTypeDate DATE NOT NULL,
PRIMARY KEY(userID,pageTypeID),
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(pageTypeID) REFERENCES PAGE_TYPE(pageTypeID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO CREATES VALUES(100000,1,'2016-10-11');
INSERT INTO CREATES VALUES(200000,1,'2012-05-21');
INSERT INTO CREATES VALUES(300000,4,'2010-06-08');
INSERT INTO CREATES VALUES(400000,3,'2014-09-19');
INSERT INTO CREATES VALUES(500000,7,'2018-12-10');

CREATE TABLE CONNECTING(
userID INT NOT NULL,
pageTypeID INT NOT NULL,
connectionDate DATE NOT NULL,
PRIMARY KEY(userID,pageTypeID),
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(pageTypeID) REFERENCES PAGE_TYPE(pageTypeID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO CONNECTING VALUES(9,100000,'2017-10-30');
INSERT INTO CONNECTING VALUES(8,100000,'2017-05-13');
INSERT INTO CONNECTING VALUES(1,200000,'2016-02-07');
INSERT INTO CONNECTING VALUES(6,300000,'2015-03-06');
INSERT INTO CONNECTING VALUES(7,400000,'2018-09-16');
INSERT INTO CONNECTING VALUES(2,400000,'2017-11-25');
INSERT INTO CONNECTING VALUES(9,200000,'2018-10-02');
INSERT INTO CONNECTING VALUES(8,700000,'2017-01-15');
INSERT INTO CONNECTING VALUES(10,200000,'2016-02-07');
INSERT INTO CONNECTING VALUES(6,500000,'2015-03-06');
INSERT INTO CONNECTING VALUES(7,600000,'2018-09-16');
INSERT INTO CONNECTING VALUES(8,400000,'2017-11-25');


CREATE TABLE JOB_POST(
jobID INT NOT NULL,
jobPosterID INT NOT NULL, /*isi paylasan pagetype*/
jobDescription TEXT NOT NULL,
PRIMARY KEY(jobID),
FOREIGN  KEY(jobPosterID) REFERENCES PAGE_TYPE(pageTypeID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO JOB_POST VALUES(55,700000,'2 yıl deneyimli yazılım mühendisi alınacaktır.'); /*700000 nolu business iş ilanı paylaşıyor*/
INSERT INTO JOB_POST VALUES(41,300000,'Restorasyon için mimar aranıyor.'); 
INSERT INTO JOB_POST VALUES(84,600000,'Fabrikada denetimci olacak gıda mühendisleri aranıyor.'); 

CREATE TABLE REQUIRED(  /*ilandaki iş gereksinimleri*/
jobID INT NOT NULL,
requiredInfo VARCHAR(300) NOT NULL,
PRIMARY KEY(jobID,requiredInfo),
FOREIGN KEY (jobID) REFERENCES JOB_POST(jobID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO REQUIRED VALUES(55,'java veya c++ bilen yazılımcı');
INSERT INTO REQUIRED VALUES(55,'İngilizce seviyesi B2 olmalı');
INSERT INTO REQUIRED VALUES(41,'En az 2 yıl deneyim aranıyor.');
INSERT INTO REQUIRED VALUES(41,'Erkekler için askerlik yapılmış olmalı.');
INSERT INTO REQUIRED VALUES(84,'Microsoft office programlarını ileri seviyede kullanabilen.');


CREATE TABLE REQUESTS(
jobID INT NOT NULL,
userID INT NOT NULL,
requestDate DATE NOT NULL,
PRIMARY KEY(jobID,userID),
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (jobID) REFERENCES JOB_POST(jobID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO REQUESTS VALUES(55,2,'2018-10-25');
INSERT INTO REQUESTS VALUES(55,1,'2018-10-22');
INSERT INTO REQUESTS VALUES(84,9,'2018-06-03');
INSERT INTO REQUESTS VALUES(41,4,'2018-12-13');


CREATE TABLE lREFERENCES(
userID INT NOT NULL, /*referans olan kişi*/
referencedID INT NOT NULL, /*kime referans olunduğu*/
PRIMARY KEY(userID,referencedID),
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (referencedID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO lREFERENCES VALUES(8,1);
INSERT INTO lREFERENCES VALUES(8,2);
INSERT INTO lREFERENCES VALUES(10,2);
INSERT INTO lREFERENCES VALUES(6,1);
INSERT INTO lREFERENCES VALUES(10,8);
INSERT INTO lREFERENCES VALUES(3,7);
INSERT INTO lREFERENCES VALUES(7,1);
INSERT INTO lREFERENCES VALUES(10,9);

CREATE TABLE lFOLLOWS(
userID INT NOT NULL, /*takip eden*/
followedID INT NOT NULL, /* takip edilen*/
followDate DATE NOT NULL,
PRIMARY KEY(userID,followedID),
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (followedID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO lFOLLOWS VALUES(1,2,'2018-02-11');
INSERT INTO lFOLLOWS VALUES(5,8,'2017-05-22');
INSERT INTO lFOLLOWS VALUES(3,6,'2018-12-10');
INSERT INTO lFOLLOWS VALUES(1,10,'2018-02-21');
INSERT INTO lFOLLOWS VALUES(2,10,'2017-03-18');
INSERT INTO lFOLLOWS VALUES(10,6,'2018-12-01');
INSERT INTO lFOLLOWS VALUES(5,7,'2018-07-09');
INSERT INTO lFOLLOWS VALUES(5,3,'2017-10-29');
INSERT INTO lFOLLOWS VALUES(3,10,'2018-01-07');
INSERT INTO lFOLLOWS VALUES(2,1,'2018-03-01');
INSERT INTO lFOLLOWS VALUES(10,2,'2017-03-19');

CREATE TABLE CONNECTS(
userID INT NOT NULL,
connectedID INT NOT NULL,
CHECK (connectedID!=userID),
connectionDate DATE NOT NULL,
PRIMARY KEY(userID,connectedID),
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (connectedID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO CONNECTS VALUES(1,2,'2014-06-28'); 
INSERT INTO CONNECTS VALUES(3,8,'2016-10-22');
INSERT INTO CONNECTS VALUES(3,6,'2016-11-14');
INSERT INTO CONNECTS VALUES(1,4,'2014-10-21'); 
INSERT INTO CONNECTS VALUES(3,7,'2016-01-14');
INSERT INTO CONNECTS VALUES(5,4,'2016-11-25');
INSERT INTO CONNECTS VALUES(5,1,'2014-05-18');
INSERT INTO CONNECTS VALUES(10,8,'2016-04-03');
INSERT INTO CONNECTS VALUES(3,5,'2016-10-28');


CREATE TABLE POST(
postID INT NOT NULL,
userID INT,
pageTypeID INT,
PRIMARY KEY (postID),
FOREIGN KEY(userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(pageTypeID) REFERENCES PAGE_TYPE(pageTypeID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO POST VALUES(123,6,null);
INSERT INTO POST VALUES(124,6,null);
INSERT INTO POST VALUES(125,null,400000);
INSERT INTO POST VALUES(126,null,200000);
INSERT INTO POST VALUES(127,10,null);


CREATE TABLE POSTING( 
pageTypeID INT NOT NULL,
postID INT NOT NULL,
postingDate DATE NOT NULL,
PRIMARY KEY(postID,pageTypeID),
FOREIGN KEY (postID) REFERENCES POST(postID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(pageTypeID) REFERENCES PAGE_TYPE(pageTypeID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO POSTING VALUES(400000,125,'2018-02-15'); 
INSERT INTO POSTING VALUES(200000,126,'2018-02-15');

CREATE TABLE POSTS( 
userID INT NOT NULL,
postID INT NOT NULL,
postingDate DATE NOT NULL,
PRIMARY KEY(userID,postID),
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(postID) REFERENCES POST(postID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO POSTS VALUES(6,123,'2018-08-29');
INSERT INTO POSTS VALUES(6,124,'2018-05-13');
INSERT INTO POSTS VALUES(10,127,'2017-12-19');

CREATE TABLE PHOTO(
postID INT NOT NULL,
photoDescription TEXT,  
PRIMARY KEY(postID),
FOREIGN KEY(postID) REFERENCES POST(postID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO PHOTO VALUES(123,'PR eğitiminden bir kare');
INSERT INTO PHOTO VALUES(126,'Oryantasyon günü...');

CREATE TABLE VIDEO(
postID INT NOT NULL,
duration TIME NOT NULL,
PRIMARY KEY(postID),
FOREIGN KEY(postID) REFERENCES POST(postID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO VIDEO VALUES(124,'00:37:18');

CREATE TABLE WRITING(
postID INT NOT NULL,
writingContent TEXT,
PRIMARY KEY(postID),
FOREIGN KEY(postID) REFERENCES POST(postID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO WRITING VALUES(125,'Türkiyede mühendislik nereye gidiyor?');
INSERT INTO WRITING VALUES(127,'The basic concepts of modern physics');

/*SELECT * FROM WRITING;*/

CREATE TABLE INTERACTION(
interactionID INT NOT NULL,
userID INT, /*interaction veren kişi*/
cvID INT, /*alan*/
pageTypeID INT, /*interaction veren*/
postID INT, 
PRIMARY KEY(interactionID),
FOREIGN KEY(userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(pageTypeID) REFERENCES PAGE_TYPE(pageTypeID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(cvID) REFERENCES CV(cvID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(postID) REFERENCES POST(postID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO INTERACTION VALUES(885,1,40,null,null);
INSERT INTO INTERACTION VALUES(886,2,40,null,null);
INSERT INTO INTERACTION VALUES(887,6,20,null,null);
INSERT INTO INTERACTION VALUES(888,10,20,null,null);
INSERT INTO INTERACTION VALUES(889,3,null,null,123);
INSERT INTO INTERACTION VALUES(890,8,30,null,null);
INSERT INTO INTERACTION VALUES(891,null,null,200000,123);
INSERT INTO INTERACTION VALUES(892,6,30,null,null);
INSERT INTO INTERACTION VALUES(893,4,null,null,126);
INSERT INTO INTERACTION VALUES(894,2,null,null,125);
INSERT INTO INTERACTION VALUES(895,null,null,500000,127);
INSERT INTO INTERACTION VALUES(896,10,null,null,127);
INSERT INTO INTERACTION VALUES(897,1,null,null,123);
INSERT INTO INTERACTION VALUES(898,null,null,500000,125);
INSERT INTO INTERACTION VALUES(899,5,null,null,125);

CREATE TABLE lLIKE(
interactionID INT NOT NULL,
likeType VARCHAR(15) NOT NULL DEFAULT 'like',
PRIMARY KEY(interactionID),
FOREIGN KEY (interactionID) REFERENCES INTERACTION(interactionID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO lLIKE VALUES(889,'like');
INSERT INTO lLIKE VALUES(897,'love');


CREATE TABLE lCOMMENT(
interactionID INT NOT NULL,
content VARCHAR(100) NOT NULL,
PRIMARY KEY(interactionID),
FOREIGN KEY (interactionID) REFERENCES INTERACTION(interactionID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO lCOMMENT VALUES(894,'güzel etkinlik, tebrikler...');
INSERT INTO lCOMMENT VALUES(895,'what a good perspective!');
INSERT INTO lCOMMENT VALUES(896,'thank you.');

CREATE TABLE TAG(
interactionID INT NOT NULL,
taggedFriendID INT NOT NULL,
PRIMARY KEY(interactionID),
FOREIGN KEY (interactionID) REFERENCES INTERACTION(interactionID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(taggedFriendID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO TAG VALUES(893,1);
INSERT INTO TAG VALUES(898,3);


CREATE TABLE lSHARE(
interactionID INT NOT NULL,
description TEXT NOT NULL,
PRIMARY KEY(interactionID),
FOREIGN KEY (interactionID) REFERENCES INTERACTION(interactionID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO lSHARE VALUES(891,'takipçimizden gelen bir gönderi');
INSERT INTO lSHARE VALUES(899,'okunması gereken bir paylaşım..');

CREATE TABLE RATE(
interactionID INT NOT NULL,
rateInfo SMALLINT NOT NULL,
PRIMARY KEY(interactionID),
FOREIGN KEY (interactionID) REFERENCES INTERACTION(interactionID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

ALTER TABLE RATE ADD CHECK (rateInfo<=5);

INSERT INTO RATE VALUES(888,3); 
INSERT INTO RATE VALUES(890,5);
INSERT INTO RATE VALUES(892,2);
INSERT INTO RATE VALUES(885,5);
INSERT INTO RATE VALUES(886,4);
INSERT INTO RATE VALUES(887,1);

CREATE TABLE INTERACTS(
userID INT NOT NULL,
interactionID INT NOT NULL,
interactionDate DATE NOT NULL,
PRIMARY KEY(interactionID,userID),
FOREIGN KEY (interactionID) REFERENCES INTERACTION(interactionID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO INTERACTS VALUES(3,885,'2016-09-25');
INSERT INTO INTERACTS VALUES(8,886,'2018-01-12');
INSERT INTO INTERACTS VALUES(6,887,'2018-04-23');
INSERT INTO INTERACTS VALUES(4,888,'2017-05-11');
INSERT INTO INTERACTS VALUES(3,889,'2016-03-27');
INSERT INTO INTERACTS VALUES(8,890,'2017-10-29');
INSERT INTO INTERACTS VALUES(6,892,'2018-08-21');
INSERT INTO INTERACTS VALUES(4,893,'2017-05-07');
INSERT INTO INTERACTS VALUES(2,894,'2018-01-09');
INSERT INTO INTERACTS VALUES(6,896,'2018-03-18');
INSERT INTO INTERACTS VALUES(4,897,'2017-04-16');
INSERT INTO INTERACTS VALUES(2,899,'2018-12-01');

CREATE TABLE INTERACTING(
pageTypeID INT NOT NULL,
interactionID INT NOT NULL,
interDate DATE NOT NULL,
PRIMARY KEY(interactionID,pageTypeID),
FOREIGN KEY (interactionID) REFERENCES INTERACTION(interactionID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (pageTypeID) REFERENCES PAGE_TYPE(pageTypeID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO INTERACTING VALUES(200000,891,'2017-08-19');
INSERT INTO INTERACTING VALUES(200000,895,'2018-07-10');
INSERT INTO INTERACTING VALUES(200000,898,'2017-01-14');

CREATE TABLE GETS(
postID INT NOT NULL,
interactionID INT NOT NULL,
interacDate DATE NOT NULL,
PRIMARY KEY(interactionID,postID),
FOREIGN KEY (interactionID) REFERENCES INTERACTION(interactionID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (postID) REFERENCES POST(postID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO GETS VALUES(123,889,'2016-09-25');
INSERT INTO GETS VALUES(123,891,'2017-08-19');
INSERT INTO GETS VALUES(126,893,'2017-05-10');
INSERT INTO GETS VALUES(125,894,'2018-01-14');
INSERT INTO GETS VALUES(127,895,'2017-07-12');
INSERT INTO GETS VALUES(127,896,'2018-10-19');
INSERT INTO GETS VALUES(123,897,'2017-01-30');
INSERT INTO GETS VALUES(125,898,'2018-01-26');
INSERT INTO GETS VALUES(125,899,'2018-06-17');


CREATE TABLE MESSAGE(
userID INT NOT NULL,  
messageID INT NOT NULL,
messageContent TEXT NOT NULL,
isSeen BOOL,
PRIMARY KEY(messageID),
FOREIGN KEY(userID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO MESSAGE VALUES(1,555,'İşe alım süreçleri hakkında bir içerik paylaşabilir misiniz? Teşekkürler...',1);
INSERT INTO MESSAGE VALUES(2,556,'How can I read all the articles that you wrote?',0);
INSERT INTO MESSAGE VALUES(3,557,'Dil farklılıklarının iletişimde yarattığı etkiler üzerine size bir sorum var.',1);
INSERT INTO MESSAGE VALUES(8,558,'Buyurun hanımefendi?',0);
INSERT INTO MESSAGE VALUES(3,559,'müsait bir vaktinizde konuyu yüz yüze görüşelim mi?',1);
INSERT INTO MESSAGE VALUES(4,560,'merhaba :)',1);

CREATE TABLE ALICI(
messageID INT NOT NULL,
aliciID INT NOT NULL,
PRIMARY KEY(messageID,aliciID),
FOREIGN KEY(messageID) REFERENCES MESSAGE(messageID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(aliciID) REFERENCES USER(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO ALICI VALUES(555,6);
INSERT INTO ALICI VALUES(556,10);
INSERT INTO ALICI VALUES(557,8);
INSERT INTO ALICI VALUES(558,3);
INSERT INTO ALICI VALUES(559,4);
INSERT INTO ALICI VALUES(560,2);

/*SELECT STATEMENTS*/

/*sertifikalı en az 1 lesson verisi olan kullanıcının bilgileri*/
SELECT DISTINCT firstName, lastName 
FROM USER, LESSON, CV
WHERE LESSON.cvID = CV.cvID
	AND CV.userID = USER.userID
    AND LESSON.isCertificated=1;

/*mevcut interactionı olmayan postlar hangileri? */ 
SELECT postID FROM POST p WHERE
NOT EXISTS(SELECT * 
FROM INTERACTION i
WHERE i.postID = p.postID);

/*user tablosu ile info tablosu arası join*/
SELECT DISTINCT INFO.contact_info, USER.firstName,USER.lastName
FROM USER
INNER JOIN INFO ON USER.userID=INFO.userID;

/* Türkiyede yaşayan, muhendis unvanı olan ve old position bilgisi girmemis kisilerin isimleri?*/
SELECT firstName,lastName
FROM USER as u
WHERE (u.title='engineer' AND u.country='England') AND NOT EXISTS(SELECT * FROM OLD_POSITIONS as o WHERE o.userID=u.userID);

/*her user kacar kisiyi takip ediyor?*/
SELECT userID, COUNT(*) as takipEttikleri
FROM lFOLLOWS
group by userID;

/*kimler ingilizce konusabiliyor, ne seviyede? */

SELECT userID,languageLevel
FROM lLANGUAGE,CV
WHERE languageName='English' AND CV.cvID = lLANGUAGE.cvID;

/*her user kacar post paylasıyor?*/
SELECT userID,COUNT(*) AS postSayisi
FROM POST
GROUP BY userID;

/*profil guclerine gore kullanıcıları azalan sırada sırala,profil gucu aynı olanlar icin alfabetik sıra onceligi esas alınıyor*/
SELECT firstName,lastName,powerOfProfile
FROM USER
ORDER BY powerOfProfile DESC, firstName ASC;

/*odul almıs kullanıcıların bilgileri*/
SELECT firstName as isim,lastName as soyisim,sector,currentPosition as guncelPozisyon
FROM HONOURSAWARDS,CV,USER
WHERE CV.cvID = HONOURSAWARDS.cvID AND CV.userID=USER.userID;

/*herhangi bir kullanıcıya referans olan kullanıcıların egitim bilgileri*/
SELECT DISTINCT u.firstName,u.lastName, E.education as EGITIM_BILGISI, s.firstName as ad, s.lastName as soyad, D.education as egitim_bilgisi
FROM lREFERENCES,EDU AS E, EDU AS D,USER as u,user as s
WHERE lREFERENCES.userID=u.userID AND E.userID = u.userID AND lREFERENCES.referencedID = s.userID AND D.userID=s.userID;


/*update DELETE*/
UPDATE PROJECT
SET projectTitle='parcacık hızlandırıcı'
where cvID=100;
DELETE FROM PROJECT WHERE cvID=20;


DELETE from USER WHERE summary='bir mimar';
UPDATE USER
SET summary='an architecture' WHERE summary=null;


UPDATE lPAGE
SET pageType='tanınmıs kisi'
WHERE pageTypeID=200000;
delete from lPAGE WHERE pageTypeID=200000;
